# .bash_profile

unset GOOS;
unset GOARCH;
export GOROOT="/Users/tstclair/.gimme/versions/go1.7.5.darwin.amd64";
export GOLOCAL="/Users/tstclair/work/spaces/Go"
export GOPATH=/mnt/work/spaces/Go
export SCRIPTS=$HOME/work/spaces/bashrc/scripts
export PATH="/Users/tstclair/.gimme/versions/go1.7.5.darwin.amd64/bin:${GOLOCAL}/bin:${SCRIPTS}:${PATH}";
export GIMME_ENV="/Users/tstclair/.gimme/envs/go1.7.5.env"

go version >&2;
